import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import axios from "axios";
import { avanzarOnboarding, completarOnboarding, obtenerOnboarding } from "../services/onboardingService";
import { actualizarMiPerfil } from "../services/profesionalService";
import { crearMiPrestacion, obtenerMisPrestaciones } from "../services/prestacionService";
import { crearMiDisponibilidad, obtenerMisDisponibilidades } from "../services/disponibilidadService";
import type { OnboardingStep } from "../types/auth";
import type { OnboardingEstado } from "../types/onboarding";
import type { Prestacion } from "../types/prestacion";
import type { Disponibilidad } from "../types/disponibilidad";
import "./Onboarding.css";
import { rutaOnboarding } from "../utils/onboarding";

const DIAS = ["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];

export default function OnboardingProfesional({ pasoRuta, onNavegar, onCompletado }: { pasoRuta: OnboardingStep; onNavegar:(ruta:string)=>void; onCompletado:()=>void }) {
  const [estado,setEstado]=useState<OnboardingEstado|null>(null); const [mensaje,setMensaje]=useState(""); const [cargando,setCargando]=useState(true); const [prestaciones,setPrestaciones]=useState<Prestacion[]>([]); const [disponibilidades,setDisponibilidades]=useState<Disponibilidad[]>([]);
  const [perfil,setPerfil]=useState({nombre:"",apellido:"",telefono:"",email:"",matricula:""});
  const [prestacion,setPrestacion]=useState({nombre:"",duracion_minutos:"30",precio:"",modalidad:"presencial" as "presencial"|"virtual"});
  const [horario,setHorario]=useState({dia_semana:"0",hora_inicio:"09:00",hora_fin:"13:00"});
  useEffect(()=>{ let activo=true; void obtenerOnboarding().then(async e=>{if(!activo)return;if(e.onboarding_step==="completado"){onCompletado();return;} setEstado(e);setPerfil({nombre:e.perfil.nombre,apellido:e.perfil.apellido,telefono:e.perfil.telefono??"",email:e.perfil.email??"",matricula:e.perfil.matricula}); if(rutaOnboarding(e.onboarding_step)!==window.location.pathname) onNavegar(rutaOnboarding(e.onboarding_step)); const [p,d]=await Promise.all([obtenerMisPrestaciones(),obtenerMisDisponibilidades()]);if(activo){setPrestaciones(p);setDisponibilidades(d);}}).catch(()=>setMensaje("No pudimos cargar tu onboarding.")).finally(()=>setCargando(false));return()=>{activo=false};},[onCompletado,onNavegar]);
  async function avanzar(siguiente:OnboardingStep){setCargando(true);setMensaje("");try{const nuevo=await avanzarOnboarding(siguiente);setEstado(nuevo);onNavegar(rutaOnboarding(nuevo.onboarding_step));}catch(e){setMensaje(errorTexto(e));}finally{setCargando(false)}}
  async function guardarPerfil(e:FormEvent){e.preventDefault();setCargando(true);try{await actualizarMiPerfil({...perfil,telefono:perfil.telefono||null,email:perfil.email||null,especialidades:estado?.perfil.especialidades.map(x=>({especialidad_id:x.especialidad_id,duracion_turno_minutos:x.duracion_turno_minutos??30}))});await avanzar("prestaciones");}catch(x){setMensaje(errorTexto(x));setCargando(false)}}
  async function agregarPrestacion(e:FormEvent){e.preventDefault();if(!estado)return;setCargando(true);try{const nueva=await crearMiPrestacion({nombre:prestacion.nombre,duracion_minutos:Number(prestacion.duracion_minutos),precio:Number(prestacion.precio),modalidad:prestacion.modalidad,especialidad_id:estado.perfil.especialidades[0].especialidad_id});setPrestaciones(p=>[...p,nueva]);setPrestacion({...prestacion,nombre:"",precio:""});}catch(x){setMensaje(errorTexto(x));}finally{setCargando(false)}}
  async function agregarHorario(e:FormEvent){e.preventDefault();setCargando(true);try{const nuevo=await crearMiDisponibilidad({dia_semana:Number(horario.dia_semana),hora_inicio:horario.hora_inicio,hora_fin:horario.hora_fin});setDisponibilidades(d=>[...d,nuevo]);}catch(x){setMensaje(errorTexto(x));}finally{setCargando(false)}}
  async function finalizar(){setCargando(true);try{await completarOnboarding();onCompletado();}catch(x){setMensaje(errorTexto(x));setCargando(false)}}
  if(cargando&&!estado)return <main className="pagina-onboarding"><p>Preparando tu cuenta…</p></main>;
  return <main className="pagina-onboarding"><section className="onboarding-shell"><header className="onboarding-top"><img src="/brand/mediturnos-logo-horizontal.svg" alt="Turnelia"/><span>Paso {Math.min(["perfil","prestaciones","disponibilidad","listo"].indexOf(pasoRuta)+1,4)} de 4</span></header><div className="onboarding-card">
    {pasoRuta==="perfil"&&<form className="onboarding-form" onSubmit={guardarPerfil}><h1>Revisá tu perfil</h1><p>Estos datos identifican tu actividad profesional.</p><div className="onboarding-grid"><label>Nombre<input value={perfil.nombre} onChange={e=>setPerfil({...perfil,nombre:e.target.value})} required/></label><label>Apellido<input value={perfil.apellido} onChange={e=>setPerfil({...perfil,apellido:e.target.value})} required/></label><label>Matrícula<input value={perfil.matricula} onChange={e=>setPerfil({...perfil,matricula:e.target.value})} required/></label><label>Teléfono<input value={perfil.telefono} onChange={e=>setPerfil({...perfil,telefono:e.target.value})}/></label><label className="ancho-completo">Email de contacto<input type="email" value={perfil.email} onChange={e=>setPerfil({...perfil,email:e.target.value})}/></label></div><button disabled={cargando}>Continuar</button></form>}
    {pasoRuta==="prestaciones"&&<div><h1>Configurá tus prestaciones</h1><p>Podés cargar ahora los servicios que ofrecés o hacerlo más adelante desde Mis prestaciones.</p><form className="onboarding-inline" onSubmit={agregarPrestacion}><input aria-label="Nombre de la prestación" placeholder="Ej. Consulta inicial" value={prestacion.nombre} onChange={e=>setPrestacion({...prestacion,nombre:e.target.value})} required/><input aria-label="Duración" type="number" min="10" max="240" value={prestacion.duracion_minutos} onChange={e=>setPrestacion({...prestacion,duracion_minutos:e.target.value})}/><input aria-label="Precio" type="number" min="0" step="0.01" placeholder="Precio" value={prestacion.precio} onChange={e=>setPrestacion({...prestacion,precio:e.target.value})} required/><button disabled={cargando}>Agregar prestación</button></form><ul className="onboarding-lista">{prestaciones.map(p=><li key={p.id}><strong>{p.nombre}</strong><span>{p.duracion_minutos} min · ${p.precio}</span></li>)}</ul><Acciones onContinuar={()=>avanzar("disponibilidad")} cargando={cargando}/></div>}
    {pasoRuta==="disponibilidad"&&<div><h1>Configurá tus horarios de atención</h1><p>Podés hacerlo ahora o más adelante desde Mi disponibilidad. Tus horarios se pueden modificar cuando quieras.</p><form className="onboarding-inline" onSubmit={agregarHorario}><select aria-label="Día" value={horario.dia_semana} onChange={e=>setHorario({...horario,dia_semana:e.target.value})}>{DIAS.map((d,i)=><option value={i} key={d}>{d}</option>)}</select><input aria-label="Hora de inicio" type="time" value={horario.hora_inicio} onChange={e=>setHorario({...horario,hora_inicio:e.target.value})}/><input aria-label="Hora de fin" type="time" value={horario.hora_fin} onChange={e=>setHorario({...horario,hora_fin:e.target.value})}/><button disabled={cargando}>Agregar horario</button></form><ul className="onboarding-lista">{disponibilidades.map(d=><li key={d.id}><strong>{DIAS[d.dia_semana]}</strong><span>{d.hora_inicio.slice(0,5)} a {d.hora_fin.slice(0,5)}</span></li>)}</ul><Acciones onContinuar={()=>avanzar("listo")} cargando={cargando}/></div>}
    {pasoRuta==="listo"&&<div className="onboarding-listo"><span aria-hidden="true">✓</span><h1>Tu cuenta está lista</h1><p>Ya podés empezar a gestionar tu consulta con Turnelia.</p><button onClick={finalizar} disabled={cargando}>Ir a mi panel</button></div>}
    {mensaje&&<p className="onboarding-error" role="alert">{mensaje}</p>}
  </div></section></main>;
}
function Acciones({onContinuar,cargando}:{onContinuar:()=>void;cargando:boolean}){return <div className="onboarding-acciones"><button onClick={onContinuar} disabled={cargando}>Continuar</button><button className="boton-omitir" onClick={onContinuar} disabled={cargando}>Omitir por ahora</button></div>}
function errorTexto(error:unknown){const detalle=axios.isAxiosError(error)?error.response?.data?.detail:null;return typeof detalle==="string"?detalle:"No pudimos guardar los cambios."}
