import { useEffect, useState } from "react";
import axios from "axios";
import type { ReservaOnlineConfig } from "../types/reservaOnline";
import { actualizarHabilitacionOnline, actualizarReservaOnline, obtenerReservaOnline } from "../services/reservaOnlineService";
import "./ReservaOnlinePanel.css";

export default function ReservaOnlinePanel() {
  const [config, setConfig] = useState<ReservaOnlineConfig | null>(null);
  const [cargando, setCargando] = useState(true); const [guardando, setGuardando] = useState(false); const [error, setError] = useState(""); const [mensaje, setMensaje] = useState("");
  const cargar = () => { setCargando(true); setError(""); void obtenerReservaOnline().then(setConfig).catch(() => setError("No pudimos cargar la configuración de reserva online.")).finally(() => setCargando(false)); };
  useEffect(cargar, []);
  async function alternarPrincipal() { if (!config || guardando) return; setGuardando(true); setError(""); try { setConfig(await actualizarReservaOnline(!config.reserva_online_activa)); setMensaje(config.reserva_online_activa ? "Las reservas online están desactivadas." : "Las reservas online están activadas."); } catch { setError("No pudimos actualizar las reservas online."); } finally { setGuardando(false); } }
  async function alternarPrestacion(id: string, activa: boolean) { if (!config) return; try { const actualizada = await actualizarHabilitacionOnline(id, activa); setConfig({...config, prestaciones: config.prestaciones.map(p => p.identificador_publico === id ? {...p, ...actualizada} : p)}); setMensaje(activa ? "Prestación habilitada para reserva online." : "Prestación deshabilitada para reserva online."); } catch (e) { setError(axios.isAxiosError(e) && e.response?.status === 409 ? "Esta prestación está inactiva y no puede habilitarse para reserva online." : "No pudimos actualizar la prestación."); } }
  if (cargando) return <section className="reserva-online-panel" aria-busy="true"><p>Cargando configuración de reserva online…</p></section>;
  if (error && !config) return <section className="reserva-online-panel" role="alert"><h2>Reserva online</h2><p>{error}</p><button type="button" onClick={cargar}>Reintentar</button></section>;
  if (!config) return null;
  const habilitadas = config.prestaciones.filter(p => p.activa && p.habilitada_online).length;
  return <section className="reserva-online-panel" aria-labelledby="reserva-online-titulo"><div className="reserva-online-heading"><div><p className="reserva-online-kicker">Configuración</p><h2 id="reserva-online-titulo">Reserva online</h2><p>Controlá cómo pueden reservar tus pacientes desde tu enlace público.</p></div><button type="button" className={`reserva-online-switch ${config.reserva_online_activa ? "is-on" : ""}`} aria-pressed={config.reserva_online_activa} onClick={() => void alternarPrincipal()} disabled={guardando}>{config.reserva_online_activa ? "Activadas" : "Desactivadas"}</button></div>{mensaje&&<p className="reserva-online-feedback" role="status">{mensaje}</p>}{error&&<p className="reserva-online-feedback error" role="alert">{error}</p>}<p className="reserva-online-notice">{config.reserva_online_activa ? "Los pacientes podrán ver tus prestaciones habilitadas y reservar horarios disponibles." : "Los pacientes no podrán reservar turnos desde tu enlace público."}</p>{config.url_publica&&<div className="reserva-online-link"><span>Tu enlace de reservas {config.reserva_online_activa ? "" : "· Actualmente inactivo"}</span><code>{config.url_publica}</code><div><button type="button" onClick={() => { void navigator.clipboard?.writeText(config.url_publica ?? ""); setMensaje("Enlace copiado"); }}>Copiar enlace</button><a href={config.url_publica} target="_blank" rel="noopener noreferrer">Ver página pública</a></div></div>}<div className="reserva-online-services"><h3>Prestaciones disponibles para reserva online</h3>{config.prestaciones.length===0?<p>Aún no tenés prestaciones para ofrecer online.</p>:<ul>{config.prestaciones.map(p=><li key={p.identificador_publico}><div><strong>{p.nombre}</strong><span>{p.duracion_minutos ? `${p.duracion_minutos} min · ` : ""}{p.modalidad ?? "Modalidad configurada"}</span>{!p.activa&&<small>Activá esta prestación antes de ofrecerla online.</small>}</div><button type="button" aria-label={`Reserva online para ${p.nombre}`} aria-pressed={p.habilitada_online} disabled={!p.activa} onClick={() => void alternarPrestacion(p.identificador_publico, !p.habilitada_online)}>{p.habilitada_online ? "ON" : "OFF"}</button></li>)}</ul>}</div>{config.reserva_online_activa&&habilitadas===0&&config.prestaciones.length>0&&<p className="reserva-online-warning">Tu página pública está activa, pero todavía no tenés prestaciones disponibles para reservar.</p>}<p className="reserva-online-help">Los horarios disponibles se calculan a partir de tu disponibilidad y excepciones configuradas.</p></section>;
}
