"""vincular usuarios con pacientes y profesionales

Revision ID: 1ebe81a92ee3
Revises: 7bf5463a67be
Create Date: 2026-08-02 18:29:34.640544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebe81a92ee3'
down_revision: Union[str, Sequence[str], None] = '7bf5463a67be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pacientes_usuario_id'), 'pacientes', ['usuario_id'], unique=True)
    op.create_foreign_key(None, 'pacientes', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('profesionales', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_profesionales_usuario_id'), 'profesionales', ['usuario_id'], unique=True)
    op.create_foreign_key(None, 'profesionales', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profesionales', type_='foreignkey')
    op.drop_index(op.f('ix_profesionales_usuario_id'), table_name='profesionales')
    op.drop_column('profesionales', 'usuario_id')
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.drop_index(op.f('ix_pacientes_usuario_id'), table_name='pacientes')
    op.drop_column('pacientes', 'usuario_id')
    # ### end Alembic commands ###
