"""migracion inicial

Revision ID: 27fcc53b0b8c
Revises: 
Create Date: 2026-08-01 18:48:31.940193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fcc53b0b8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_turno_minutos', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidades_id'), 'especialidades', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('obra_social', sa.String(length=100), nullable=True),
    sa.Column('numero_afiliado', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('profesionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_profesionales_id'), 'profesionales', ['id'], unique=False)
    op.create_table('disponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disponibilidades_id'), 'disponibilidades', ['id'], unique=False)
    op.create_index(op.f('ix_disponibilidades_profesional_id'), 'disponibilidades', ['profesional_id'], unique=False)
    op.create_table('prestaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestaciones_id'), 'prestaciones', ['id'], unique=False)
    op.create_table('profesionales_especialidades',
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.Column('duracion_turno_minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('profesional_id', 'especialidad_id')
    )
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('prestacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['prestacion_id'], ['prestaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_fecha_hora'), 'turnos', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_fecha_hora'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_table('profesionales_especialidades')
    op.drop_index(op.f('ix_prestaciones_id'), table_name='prestaciones')
    op.drop_table('prestaciones')
    op.drop_index(op.f('ix_disponibilidades_profesional_id'), table_name='disponibilidades')
    op.drop_index(op.f('ix_disponibilidades_id'), table_name='disponibilidades')
    op.drop_table('disponibilidades')
    op.drop_index(op.f('ix_profesionales_id'), table_name='profesionales')
    op.drop_table('profesionales')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_especialidades_id'), table_name='especialidades')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
