"""simplificar relacion profesional especialidad

Revision ID: 3955e34c53d6
Revises: 589b2166dd21
Create Date: 2026-08-01 14:57:00.578280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3955e34c53d6'
down_revision: Union[str, Sequence[str], None] = '589b2166dd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesionales_especialidades', 'duracion_turno_minutos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesionales_especialidades', sa.Column('duracion_turno_minutos', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
