"""crear tabla disponibilidades

Revision ID: 9725812fae76
Revises: b82ad3d4ac97
Create Date: 2026-08-01 16:58:36.879860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9725812fae76'
down_revision: Union[str, Sequence[str], None] = 'b82ad3d4ac97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disponibilidades_id'), 'disponibilidades', ['id'], unique=False)
    op.create_index(op.f('ix_disponibilidades_profesional_id'), 'disponibilidades', ['profesional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disponibilidades_profesional_id'), table_name='disponibilidades')
    op.drop_index(op.f('ix_disponibilidades_id'), table_name='disponibilidades')
    op.drop_table('disponibilidades')
    # ### end Alembic commands ###
