import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import type { StudyRequest, StudyRequestStatus } from "../../types/paciente";
import { cancelarStudyRequest, cerrarStudyRequest, crearStudyRequest, listarStudyRequests } from "../../services/pacienteService";
import "./PatientStudyRequests.css";
const LABELS: Record<StudyRequestStatus, string> = { pending: "Pendiente", submitted: "Resultados enviados", reviewed: "Revisado", closed: "Cerrado", cancelled: "Cancelado" };
function errorText(error: unknown) { return axios.isAxiosError(error) && typeof error.response?.data?.detail === "string" ? error.response.data.detail : "No se pudo completar la operación."; }
export default function PatientStudyRequests({ patientId }: { patientId: number }) {
  const [items, setItems] = useState<StudyRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [instructions, setInstructions] = useState(""); const [saving, setSaving] = useState(false); const [actingId, setActingId] = useState<number | null>(null); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await listarStudyRequests(patientId)) ?? []); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [patientId]);
  useEffect(() => { setItems([]); setEditing(false); setTitle(""); setInstructions(""); void load(); }, [load]);
  async function create() { if (!title.trim() || saving) return; setSaving(true); setError(""); try { const item = await crearStudyRequest(patientId, { title, instructions: instructions.trim() || null, turno_id: null, expires_at: null }); setItems((current) => [item, ...current]); setTitle(""); setInstructions(""); setEditing(false); setMessage("Solicitud de estudio creada correctamente."); } catch (e) { setError(errorText(e)); } finally { setSaving(false); } }
  async function transition(item: StudyRequest, action: "cancel" | "close") { if (actingId !== null || !window.confirm(action === "cancel" ? "¿Cancelar esta solicitud?" : "¿Cerrar esta solicitud?")) return; setActingId(item.id); try { const updated = action === "cancel" ? await cancelarStudyRequest(patientId, item.id) : await cerrarStudyRequest(patientId, item.id); setItems((current) => current.map((currentItem) => currentItem.id === item.id ? updated : currentItem)); } catch (e) { setError(errorText(e)); } finally { setActingId(null); } }
  return <section className="patient-study-requests"><header><div><span>Seguimiento clínico</span><h3>Estudios solicitados</h3></div>{!editing && <button type="button" className="pacientes-boton primario" onClick={() => setEditing(true)}>Solicitar estudio</button>}</header>{editing && <form className="study-request-form" onSubmit={(event) => { event.preventDefault(); void create(); }}><label>Título<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={200} required /></label><label>Indicaciones<textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} maxLength={5000} rows={4} /></label><div><button type="button" className="pacientes-boton secundario" onClick={() => setEditing(false)}>Cancelar</button><button className="pacientes-boton primario" disabled={saving || !title.trim()}>{saving ? "Guardando…" : "Crear solicitud"}</button></div></form>}{message && <p role="status" className="pacientes-feedback exito">{message}</p>}{error && <p role="alert" className="pacientes-feedback error">{error}</p>}{loading ? <p>Cargando solicitudes...</p> : items.length === 0 ? <p className="study-request-empty">No hay estudios solicitados.</p> : <ul className="study-request-list">{items.map((item) => <li key={item.id}><div><strong>{item.title}</strong>{item.instructions && <p>{item.instructions}</p>}<time>{new Intl.DateTimeFormat("es-AR").format(new Date(item.requested_at))}</time></div><div><span className={`study-request-status status-${item.status}`}>{LABELS[item.status]}</span>{item.status === "pending" && <span className="study-request-actions"><button type="button" className="pacientes-boton enlace" disabled={actingId !== null} onClick={() => void transition(item, "cancel")}>Cancelar</button><button type="button" className="pacientes-boton enlace" disabled={actingId !== null} onClick={() => void transition(item, "close")}>Cerrar</button></span>}</div></li>)}</ul>}</section>;
}
