import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import type { PatientDocument, PatientDocumentCategory } from "../../types/paciente";
import { confirmarDocumento, crearIntentDocumento, eliminarDocumento, listarDocumentosPaciente, obtenerUrlDocumento } from "../../services/pacienteService";
import "./PatientDocuments.css";
const CATEGORIES: Array<[PatientDocumentCategory, string]> = [["laboratory", "Laboratorio"], ["imaging", "Imágenes"], ["order", "Orden"], ["report", "Informe"], ["prescription", "Receta / Prescripción"], ["other", "Otro"]];
const MAX_SIZE = 10 * 1024 * 1024;
function errorText(error: unknown) { return axios.isAxiosError(error) && typeof error.response?.data?.detail === "string" ? error.response.data.detail : "No se pudo completar la operación."; }
function sizeText(size: number | null) { return size == null ? "Tamaño no informado" : `${(size / 1024 / 1024).toFixed(2)} MB`; }
export default function PatientDocuments({ patientId }: { patientId: number }) {
  const [documents, setDocuments] = useState<PatientDocument[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [file, setFile] = useState<File | null>(null); const [category, setCategory] = useState<PatientDocumentCategory>("other"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setDocuments((await listarDocumentosPaciente(patientId)) ?? []); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [patientId]);
  useEffect(() => { setDocuments([]); setFile(null); setMessage(""); void load(); }, [patientId, load]);
  async function upload() { if (!file || saving) return; if (!file.type || file.size <= 0 || file.size > MAX_SIZE) { setError("El archivo debe tener un tipo válido y pesar hasta 10 MB."); return; } setSaving(true); setError(""); setMessage(""); try { const intent = await crearIntentDocumento(patientId, { filename: file.name, mime_type: file.type, size_bytes: file.size, category }); const response = await fetch(intent.upload_url, { method: "PUT", headers: { "Content-Type": intent.required_content_type }, body: file }); if (!response.ok) throw new Error("upload"); await confirmarDocumento(patientId, intent.document_id); setFile(null); setMessage("Documento adjuntado correctamente."); await load(); } catch (e) { setError(e instanceof Error && e.message === "upload" ? "No se pudo cargar el archivo." : errorText(e)); } finally { setSaving(false); } }
  async function download(id: number) { try { window.open(await obtenerUrlDocumento(patientId, id), "_blank", "noopener,noreferrer"); } catch (e) { setError(errorText(e)); } }
  async function remove(id: number) { if (!window.confirm("¿Eliminar este documento de la historia clínica?")) return; try { await eliminarDocumento(patientId, id); setDocuments((items) => items.filter((item) => item.id !== id)); } catch (e) { setError(errorText(e)); } }
  const safeDocuments = documents ?? [];
  return <section className="patient-documents"><header><div><span>Historia clínica</span><h3>Documentos</h3></div></header><div className="patient-documents-upload"><label>Archivo<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><label>Categoría<select value={category} onChange={(e) => setCategory(e.target.value as PatientDocumentCategory)}>{CATEGORIES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="button" className="pacientes-boton primario" disabled={!file || saving} onClick={() => void upload()}>{saving ? "Cargando…" : "Adjuntar documento"}</button></div>{message && <p role="status" className="pacientes-feedback exito">{message}</p>}{error && <p role="alert" className="pacientes-feedback error">{error}</p>}{loading ? <p>Cargando documentos...</p> : safeDocuments.length === 0 ? <p className="documents-empty">Todavía no hay documentos disponibles.</p> : <ul className="documents-list">{safeDocuments.map((document) => <li key={document.id}><div><strong>{document.original_filename}</strong><span>{CATEGORIES.find(([value]) => value === document.category)?.[1]} · {sizeText(document.size_bytes)}</span><time>{new Intl.DateTimeFormat("es-AR").format(new Date(document.created_at))}</time></div><div><button type="button" className="pacientes-boton enlace" onClick={() => void download(document.id)}>Ver / Descargar</button><button type="button" className="pacientes-boton destructivo" onClick={() => void remove(document.id)}>Eliminar</button></div></li>)}</ul>}</section>;
}
