import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import type { StudyRequest, StudyRequestStatus, StudyReview } from "../../types/paciente";
import { cancelarStudyRequest, cerrarStudyRequest, crearStudyRequest, generarStudyAccessLink, listarStudyRequests } from "../../services/pacienteService";
import StudyReviewForm from "./StudyReviewForm";
import "./PatientStudyRequests.css";

const LABELS: Record<StudyRequestStatus, string> = { pending: "Pendiente", submitted: "Resultados enviados", reviewed: "Revisado", closed: "Cerrado", cancelled: "Cancelado" };
const errorText = (e: unknown) => axios.isAxiosError(e) && typeof e.response?.data?.detail === "string" ? e.response.data.detail : "No se pudo completar la operación.";

export default function PatientStudyRequests({ patientId }: { patientId: number }) {
  const [items, setItems] = useState<StudyRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [instructions, setInstructions] = useState(""); const [saving, setSaving] = useState(false); const [actingId, setActingId] = useState<number | null>(null); const [linkingId, setLinkingId] = useState<number | null>(null); const [reviewingId, setReviewingId] = useState<number | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await listarStudyRequests(patientId)) ?? []); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [patientId]);
  useEffect(() => { setItems([]); setEditing(false); setReviewingId(null); void load(); }, [load]);
  async function create() { if (saving || !title.trim()) return; setSaving(true); setError(""); try { const item = await crearStudyRequest(patientId, { title, instructions: instructions.trim() || null, turno_id: null, expires_at: null }); setItems((current) => [item, ...current]); setTitle(""); setInstructions(""); setEditing(false); setMessage("Solicitud de estudio creada correctamente."); } catch (e) { setError(errorText(e)); } finally { setSaving(false); } }
  async function transition(item: StudyRequest, action: "cancel" | "close") { if (actingId !== null) return; setActingId(item.id); try { const updated = action === "cancel" ? await cancelarStudyRequest(patientId, item.id) : await cerrarStudyRequest(patientId, item.id); setItems((current) => current.map((value) => value.id === item.id ? updated : value)); } catch (e) { setError(errorText(e)); } finally { setActingId(null); } }
  async function link(item: StudyRequest) { if (linkingId !== null) return; setLinkingId(item.id); try { const result = await generarStudyAccessLink(patientId, item.id); await navigator.clipboard.writeText(result.url); setMessage("Enlace copiado"); } catch (e) { setError(errorText(e)); } finally { setLinkingId(null); } }
  function saved(review: StudyReview) { setItems((current) => current.map((item) => item.id === review.study_request_id ? { ...item, status: "reviewed", reviewed_at: review.reviewed_at } : item)); setMessage("Devolución registrada correctamente."); }
  return <section className="patient-study-requests"><header><div><span>Seguimiento clínico</span><h3>Estudios solicitados</h3></div>{!editing && <button type="button" className="pacientes-boton primario" onClick={() => setEditing(true)}>Solicitar estudio</button>}</header>{editing && <form className="study-request-form" onSubmit={(e) => { e.preventDefault(); void create(); }}><label>Título<input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={200} required /></label><label>Indicaciones<textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} maxLength={5000} rows={4} /></label><button type="button" className="pacientes-boton secundario" onClick={() => setEditing(false)}>Cancelar</button><button className="pacientes-boton primario" disabled={saving || !title.trim()}>{saving ? "Guardando…" : "Crear solicitud"}</button></form>}{message && <p role="status" className="pacientes-feedback exito">{message}</p>}{error && <p role="alert" className="pacientes-feedback error">{error}</p>}{loading ? <p>Cargando solicitudes...</p> : items.length === 0 ? <p className="study-request-empty">No hay estudios solicitados.</p> : <ul className="study-request-list">{items.map((item) => <li key={item.id}><div><strong>{item.title}</strong>{item.instructions && <p>{item.instructions}</p>}<time>{new Intl.DateTimeFormat("es-AR").format(new Date(item.requested_at))}</time></div><div><span className={`study-request-status status-${item.status}`}>{LABELS[item.status]}</span>{(item.status === "submitted" || item.status === "reviewed") && <button type="button" className="pacientes-boton enlace" onClick={() => setReviewingId(reviewingId === item.id ? null : item.id)}>{reviewingId === item.id ? "Ocultar revisión" : "Revisar"}</button>}{item.status === "pending" && <><button type="button" className="pacientes-boton enlace" disabled={actingId !== null} onClick={() => void transition(item, "cancel")}>Cancelar</button><button type="button" className="pacientes-boton enlace" disabled={actingId !== null} onClick={() => void transition(item, "close")}>Cerrar</button><button type="button" className="pacientes-boton enlace" disabled={linkingId !== null} onClick={() => void link(item)}>Generar enlace</button></>}</div>{reviewingId === item.id && <StudyReviewForm patientId={patientId} request={item} onSaved={saved} />}</li>)}</ul>}</section>;
}
