import { useEffect, useState } from "react";
import axios from "axios";
import type { PatientDocument, StudyRequest, StudyReview, StudyReviewDisposition } from "../../types/paciente";
import { crearStudyReview, listarDocumentosDeStudyRequest, obtenerStudyReview, obtenerUrlDocumento } from "../../services/pacienteService";
const LABELS: Record<StudyReviewDisposition, string> = { online_response: "Respuesta online", requires_in_person: "Requiere consulta presencial", requires_teleconsultation: "Requiere teleconsulta" };
function errorText(error: unknown) { if (axios.isAxiosError(error) && typeof error.response?.data?.detail === "string") return error.response.data.detail; if (typeof error === "object" && error !== null && "response" in error) { const detail = (error as { response?: { data?: { detail?: unknown } } }).response?.data?.detail; if (typeof detail === "string") return detail; } return "No se pudo cargar la devolución."; }
export default function StudyReviewForm({ patientId, request, onSaved }: { patientId: number; request: StudyRequest; onSaved: (review: StudyReview) => void }) {
  const [docs, setDocs] = useState<PatientDocument[]>([]); const [review, setReview] = useState<StudyReview | null>(null); const [text, setText] = useState(""); const [disposition, setDisposition] = useState<StudyReviewDisposition>("online_response"); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void (async () => { try { setDocs(await listarDocumentosDeStudyRequest(patientId, request.id)); if (request.status === "reviewed") setReview(await obtenerStudyReview(patientId, request.id)); } catch (e) { if (request.status !== "reviewed") setError(errorText(e)); } })(); }, [patientId, request]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (saving || !text.trim()) return; setSaving(true); setError(""); try { const result = await crearStudyReview(patientId, request.id, { review_text: text, disposition }); setReview(result); onSaved(result); } catch (e) { setError(errorText(e)); } finally { setSaving(false); } }
  async function download(id: number) { try { window.open(await obtenerUrlDocumento(patientId, id), "_blank", "noopener,noreferrer"); } catch (e) { setError(errorText(e)); } }
  return <div className="study-review-form"><h4>Documentos recibidos</h4>{docs.length ? <ul>{docs.map((doc) => <li key={doc.id}><span>{doc.original_filename}</span><button type="button" className="pacientes-boton enlace" onClick={() => void download(doc.id)}>Ver / Descargar</button></li>)}</ul> : <p>No hay documentos disponibles para revisar.</p>}{review ? <div role="status"><strong>Devolución registrada correctamente.</strong><p>{review.review_text}</p><span>{LABELS[review.disposition]}</span></div> : request.status === "submitted" ? <form onSubmit={(event) => void submit(event)}><label>Devolución clínica<textarea value={text} onChange={(e) => setText(e.target.value)} maxLength={10000} rows={6} required /></label><label>Resolución<select value={disposition} onChange={(e) => setDisposition(e.target.value as StudyReviewDisposition)}>{Object.entries(LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{error && <p role="alert">{error}</p>}<button className="pacientes-boton primario" disabled={saving || !text.trim()}>{saving ? "Guardando…" : "Registrar devolución"}</button></form> : null}</div>;
}
