import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import MisPrestaciones from "../src/components/MisPrestaciones";
import * as servicio from "../src/services/prestacionService";
import * as profesional from "../src/services/profesionalService";
import * as especialidad from "../src/services/especialidadService";

vi.mock("../src/services/prestacionService");vi.mock("../src/services/profesionalService");vi.mock("../src/services/especialidadService");
const props={nombre:"Sofía",onVolver:vi.fn(),onAbrirAgenda:vi.fn(),onAbrirPacientes:vi.fn(),onAbrirDisponibilidad:vi.fn(),onAbrirPerfil:vi.fn(),onCerrarSesion:vi.fn()};
const item={id:1,nombre:"Consulta",descripcion:null,duracion_minutos:30,precio:"1000",modalidad:"presencial" as const,activa:true,profesional_id:2,especialidad_id:3};
describe("Mis prestaciones",()=>{beforeEach(()=>{vi.clearAllMocks();vi.mocked(servicio.obtenerMisPrestaciones).mockResolvedValue([]);vi.mocked(profesional.obtenerMiPerfilProfesional).mockResolvedValue({id:2,nombre:"Sofía",apellido:"R",matricula:"1",telefono:null,email:null,activo:true,especialidades:[{especialidad_id:3,duracion_turno_minutos:30}]});vi.mocked(especialidad.obtenerEspecialidades).mockResolvedValue([{id:3,nombre:"Clínica",descripcion:null,duracion_turno_minutos:30,activa:true}])});
it("muestra loading y vacío usando el endpoint propio",async()=>{render(<MisPrestaciones {...props}/>);expect(screen.getByText("Cargando prestaciones...")).toBeInTheDocument();expect(await screen.findByText("No tenés prestaciones registradas")).toBeInTheDocument();expect(servicio.obtenerMisPrestaciones).toHaveBeenCalled();expect(servicio.obtenerPrestaciones).not.toHaveBeenCalled()});
it("lista y edita una prestación",async()=>{vi.mocked(servicio.obtenerMisPrestaciones).mockResolvedValue([item]);vi.mocked(servicio.editarMiPrestacion).mockResolvedValue({...item,duracion_minutos:45});render(<MisPrestaciones {...props}/>);fireEvent.click(await screen.findByText("Gestionar"));fireEvent.change(screen.getByLabelText("Duración *"),{target:{value:"45"}});fireEvent.click(screen.getByText("Guardar cambios"));await waitFor(()=>expect(servicio.editarMiPrestacion).toHaveBeenCalledWith(1,expect.objectContaining({duracion_minutos:45}))) });
it("bloquea doble submit",async()=>{vi.mocked(servicio.obtenerMisPrestaciones).mockResolvedValue([item]);vi.mocked(servicio.crearMiPrestacion).mockReturnValue(new Promise(()=>{}));render(<MisPrestaciones {...props}/>);await screen.findByText("Consulta");fireEvent.click(screen.getByText("Nueva prestación"));fireEvent.change(screen.getByLabelText("Nombre *"),{target:{value:"Control"}});fireEvent.click(screen.getByText("Crear prestación"));expect(screen.getByText("Creando…")).toBeDisabled();expect(servicio.crearMiPrestacion).toHaveBeenCalledTimes(1)});
it("desactiva con confirmación propia",async()=>{vi.mocked(servicio.obtenerMisPrestaciones).mockResolvedValue([item]);vi.mocked(servicio.desactivarMiPrestacion).mockResolvedValue({...item,activa:false});render(<MisPrestaciones {...props}/>);fireEvent.click(await screen.findByText("Gestionar"));fireEvent.click(screen.getByText("Desactivar prestación"));fireEvent.click(screen.getByRole("button",{name:"Desactivar"}));await waitFor(()=>expect(servicio.desactivarMiPrestacion).toHaveBeenCalledWith(1))});
it("reactiva con la respuesta real y actualiza la fila",async()=>{const inactiva={...item,activa:false};vi.mocked(servicio.obtenerMisPrestaciones).mockResolvedValue([inactiva]);vi.mocked(servicio.editarMiPrestacion).mockResolvedValue({...inactiva,activa:true});render(<MisPrestaciones {...props}/>);fireEvent.click(await screen.findByText("Gestionar"));fireEvent.click(screen.getByText("Reactivar prestación"));await waitFor(()=>expect(servicio.editarMiPrestacion).toHaveBeenCalledWith(1,{activa:true}));expect(await screen.findByText("Prestación reactivada correctamente.")).toBeInTheDocument();expect(screen.getByText("Activa")).toBeInTheDocument()});
it("bloquea doble reactivación",async()=>{const inactiva={...item,activa:false};vi.mocked(servicio.obtenerMisPrestaciones).mockResolvedValue([inactiva]);vi.mocked(servicio.editarMiPrestacion).mockReturnValue(new Promise(()=>{}));render(<MisPrestaciones {...props}/>);fireEvent.click(await screen.findByText("Gestionar"));const boton=screen.getByText("Reactivar prestación");fireEvent.click(boton);expect(screen.getByText("Reactivando…")).toBeDisabled();fireEvent.click(screen.getByText("Reactivando…"));expect(servicio.editarMiPrestacion).toHaveBeenCalledTimes(1)});
it("mantiene el modal y no muestra éxito si falla",async()=>{const inactiva={...item,activa:false};vi.mocked(servicio.obtenerMisPrestaciones).mockResolvedValue([inactiva]);vi.mocked(servicio.editarMiPrestacion).mockRejectedValue(new Error("falló"));render(<MisPrestaciones {...props}/>);fireEvent.click(await screen.findByText("Gestionar"));fireEvent.click(screen.getByText("Reactivar prestación"));await waitFor(()=>expect(servicio.editarMiPrestacion).toHaveBeenCalled());expect(screen.getByText("Gestionar prestación")).toBeInTheDocument();expect(screen.queryByText("Prestación reactivada correctamente.")).not.toBeInTheDocument()});});
