import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import PatientDocuments from "../src/components/pacientes/PatientDocuments";

const service = vi.hoisted(() => ({ listar: vi.fn(), intent: vi.fn(), confirmar: vi.fn(), url: vi.fn(), eliminar: vi.fn() }));
vi.mock("../src/services/pacienteService", () => ({ listarDocumentosPaciente: service.listar, crearIntentDocumento: service.intent, confirmarDocumento: service.confirmar, obtenerUrlDocumento: service.url, eliminarDocumento: service.eliminar }));
const document = { id: 1, paciente_id: 7, original_filename: "resultado.pdf", mime_type: "application/pdf", size_bytes: 100, category: "laboratory", status: "available", created_at: "2026-08-20T12:00:00Z", available_at: "2026-08-20T12:01:00Z", uploaded_by_profesional_id: 2 } as const;
beforeEach(() => { vi.clearAllMocks(); service.listar.mockResolvedValue([]); service.confirmar.mockResolvedValue(document); service.intent.mockResolvedValue({ document_id: 2, upload_url: "https://upload.test", expires_in_seconds: 600, required_content_type: "application/pdf" }); globalThis.fetch = vi.fn().mockResolvedValue({ ok: true }) as typeof fetch; });

describe("PatientDocuments", () => {
  it("muestra vacío y lista documentos", async () => { const { rerender } = render(<PatientDocuments patientId={7} />); expect(await screen.findByText("Todavía no hay documentos disponibles.")).toBeInTheDocument(); service.listar.mockResolvedValue([document]); rerender(<PatientDocuments patientId={8} />); expect(await screen.findByText("resultado.pdf")).toBeInTheDocument(); });
  it("hace intent, PUT directo sin Authorization y confirmación", async () => { render(<PatientDocuments patientId={7} />); const file = new File(["pdf"], "resultado.pdf", { type: "application/pdf" }); fireEvent.change(screen.getByLabelText("Archivo"), { target: { files: [file] } }); fireEvent.click(screen.getByRole("button", { name: "Adjuntar documento" })); await waitFor(() => expect(service.confirmar).toHaveBeenCalled()); expect(globalThis.fetch).toHaveBeenCalledWith("https://upload.test", expect.objectContaining({ method: "PUT", headers: { "Content-Type": "application/pdf" } })); expect(JSON.stringify((globalThis.fetch as ReturnType<typeof vi.fn>).mock.calls)).not.toContain("Authorization"); });
  it("no confirma si falla el PUT y bloquea doble submit", async () => { (globalThis.fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({ ok: false }); render(<PatientDocuments patientId={7} />); const file = new File(["pdf"], "resultado.pdf", { type: "application/pdf" }); fireEvent.change(screen.getByLabelText("Archivo"), { target: { files: [file] } }); const button = screen.getByRole("button", { name: "Adjuntar documento" }); fireEvent.click(button); expect(button).toBeDisabled(); await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("No se pudo cargar")); expect(service.confirmar).not.toHaveBeenCalled(); });
  it("descarga y elimina con confirmación", async () => { service.listar.mockResolvedValue([document]); service.url.mockResolvedValue("https://download.test"); vi.spyOn(window, "open").mockImplementation(() => null); vi.spyOn(window, "confirm").mockReturnValue(true); render(<PatientDocuments patientId={7} />); await screen.findByText("resultado.pdf"); fireEvent.click(screen.getByRole("button", { name: "Ver / Descargar" })); fireEvent.click(screen.getByRole("button", { name: "Eliminar" })); await waitFor(() => expect(service.eliminar).toHaveBeenCalledWith(7, 1)); expect(localStorage.length).toBe(0); });
});
