import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import PatientStudyRequests from "../src/components/pacientes/PatientStudyRequests";
const service = vi.hoisted(() => ({ list: vi.fn(), create: vi.fn(), cancel: vi.fn(), close: vi.fn() }));
vi.mock("../src/services/pacienteService", () => ({ listarStudyRequests: service.list, crearStudyRequest: service.create, cancelarStudyRequest: service.cancel, cerrarStudyRequest: service.close }));
const pending = { id: 1, paciente_id: 7, profesional_id: 2, turno_id: null, title: "Hemograma", instructions: "En ayunas", status: "pending", requested_at: "2026-08-20T12:00:00Z", expires_at: null, submitted_at: null, reviewed_at: null, closed_at: null, cancelled_at: null, created_at: "2026-08-20T12:00:00Z", updated_at: "2026-08-20T12:00:00Z" } as const;
beforeEach(() => { vi.clearAllMocks(); service.list.mockResolvedValue([]); service.create.mockResolvedValue(pending); service.cancel.mockResolvedValue({ ...pending, status: "cancelled" }); service.close.mockResolvedValue({ ...pending, status: "closed" }); vi.spyOn(window, "confirm").mockReturnValue(true); });
describe("PatientStudyRequests", () => {
  it("muestra empty state y listado con estado", async () => { const { rerender } = render(<PatientStudyRequests patientId={7} />); expect(await screen.findByText("No hay estudios solicitados.")).toBeInTheDocument(); service.list.mockResolvedValue([pending]); rerender(<PatientStudyRequests patientId={8} />); expect(await screen.findByText("Hemograma")).toBeInTheDocument(); expect(screen.getByText("Pendiente")).toBeInTheDocument(); });
  it("crea una solicitud y permite cancelarla o cerrarla", async () => { render(<PatientStudyRequests patientId={7} />); fireEvent.click(screen.getByRole("button", { name: "Solicitar estudio" })); fireEvent.change(screen.getByLabelText("Título"), { target: { value: "  Nuevo estudio " } }); fireEvent.click(screen.getByRole("button", { name: "Crear solicitud" })); await waitFor(() => expect(service.create).toHaveBeenCalledWith(7, { title: "  Nuevo estudio ", instructions: null, turno_id: null, expires_at: null })); expect(await screen.findByText("Hemograma")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Cancelar" })); await waitFor(() => expect(service.cancel).toHaveBeenCalledWith(7, 1)); });
  it("muestra error de creación sin perder la sección", async () => { service.create.mockRejectedValue(new Error("fallo")); render(<PatientStudyRequests patientId={7} />); fireEvent.click(screen.getByRole("button", { name: "Solicitar estudio" })); fireEvent.change(screen.getByLabelText("Título"), { target: { value: "Estudio" } }); fireEvent.click(screen.getByRole("button", { name: "Crear solicitud" })); expect(await screen.findByRole("alert")).toHaveTextContent("No se pudo completar"); });
  it("cierra una solicitud pending", async () => { service.list.mockResolvedValue([pending]); render(<PatientStudyRequests patientId={7} />); await screen.findByText("Hemograma"); fireEvent.click(screen.getByRole("button", { name: "Cerrar" })); await waitFor(() => expect(service.close).toHaveBeenCalledWith(7, 1)); });
});
