import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import PatientStudyRequests from "../src/components/pacientes/PatientStudyRequests";

const service = vi.hoisted(() => ({ list: vi.fn(), review: vi.fn(), getReview: vi.fn(), docs: vi.fn(), download: vi.fn(), create: vi.fn(), cancel: vi.fn(), close: vi.fn(), link: vi.fn() }));
vi.mock("../src/services/pacienteService", () => ({ listarStudyRequests: service.list, crearStudyRequest: service.create, cancelarStudyRequest: service.cancel, cerrarStudyRequest: service.close, generarStudyAccessLink: service.link, crearStudyReview: service.review, obtenerStudyReview: service.getReview, listarDocumentosDeStudyRequest: service.docs, obtenerUrlDocumento: service.download }));
const request = { id: 3, paciente_id: 7, profesional_id: 2, turno_id: null, title: "Resonancia", instructions: null, status: "submitted", requested_at: "2026-08-20T12:00:00Z", expires_at: null, submitted_at: "2026-08-20T12:00:00Z", reviewed_at: null, closed_at: null, cancelled_at: null, created_at: "2026-08-20T12:00:00Z", updated_at: "2026-08-20T12:00:00Z" } as const;
beforeEach(() => { vi.clearAllMocks(); service.list.mockResolvedValue([request]); service.docs.mockResolvedValue([{ id: 9, original_filename: "resultado.pdf", status: "available", study_request_id: 3 }]); service.review.mockResolvedValue({ id: 5, study_request_id: 3, review_text: "Todo correcto", disposition: "requires_in_person", reviewed_at: "2026-08-20T13:00:00Z", professional_name: "Dra. Test" }); service.download.mockResolvedValue("https://download.test"); });
describe("StudyReview", () => {
  it("abre el formulario, muestra documentos y disposiciones, y guarda", async () => { render(<PatientStudyRequests patientId={7} />); expect(await screen.findByText("Resonancia")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Revisar" })); expect(await screen.findByText("resultado.pdf")).toBeInTheDocument(); expect(screen.getByRole("option", { name: "Respuesta online" })).toBeInTheDocument(); fireEvent.change(screen.getByLabelText("Devolución clínica"), { target: { value: "Todo correcto" } }); fireEvent.change(screen.getByLabelText("Resolución"), { target: { value: "requires_in_person" } }); fireEvent.click(screen.getByRole("button", { name: "Registrar devolución" })); await waitFor(() => expect(service.review).toHaveBeenCalledWith(7, 3, { review_text: "Todo correcto", disposition: "requires_in_person" })); expect(await screen.findByText("Devolución registrada correctamente.")).toBeInTheDocument(); });
  it("bloquea doble submit y conserva texto ante error", async () => { service.review.mockImplementation(() => new Promise((_, reject) => setTimeout(() => reject({ response: { data: { detail: "falló" } } }), 20))); render(<PatientStudyRequests patientId={7} />); fireEvent.click(await screen.findByRole("button", { name: "Revisar" })); fireEvent.change(await screen.findByLabelText("Devolución clínica"), { target: { value: "Texto conservado" } }); const button = screen.getByRole("button", { name: "Registrar devolución" }); fireEvent.click(button); fireEvent.click(button); expect(service.review).toHaveBeenCalledTimes(1); expect(await screen.findByDisplayValue("Texto conservado")).toBeInTheDocument(); expect(await screen.findByRole("alert")).toHaveTextContent("falló"); });
});
