import { useEffect, useState } from "react";
import { trackEvent } from "../analytics";
import { capturePostHogEvent, normalizePostHogError } from "../posthog";
import { crearReservaPublica, obtenerDisponibilidadPublica, obtenerPerfilPublico, obtenerPrestacionesPublicas, type PublicPrestacion, type PublicReserva } from "../services/publicBookingService";
import { crearWaitlistPublica } from "../services/publicWaitlistService";
import { formatoFechaHoraPublica, formatoHoraPublica } from "../utils/publicDateTime";
import "./PublicBooking.css";

type DatosPaciente = { nombre: string; apellido: string; email: string; telefono: string; dni: string };
const PACIENTE_VACIO: DatosPaciente = { nombre: "", apellido: "", email: "", telefono: "", dni: "" };

export default function PublicBooking({ slug }: { slug: string }) {
  const [perfil, setPerfil] = useState<{ nombre: string; apellido: string } | null>(null), [items, setItems] = useState<PublicPrestacion[]>([]), [sel, setSel] = useState(""), [fecha, setFecha] = useState(""), [horarios, setHorarios] = useState<string[]>([]), [hora, setHora] = useState(""), [datos, setDatos] = useState<DatosPaciente>(PACIENTE_VACIO), [estado, setEstado] = useState<"loading" | "form" | "confirmado" | "error">("loading"), [reserva, setReserva] = useState<PublicReserva | null>(null), [mensaje, setMensaje] = useState("");
  const [modoEspera, setModoEspera] = useState(false), [enviandoEspera, setEnviandoEspera] = useState(false), [esperaEnviada, setEsperaEnviada] = useState(false), [errorEspera, setErrorEspera] = useState(""), [fechaHastaEspera, setFechaHastaEspera] = useState("");
  const [waitlistTime, setWaitlistTime] = useState({ desde: "", hasta: "" });
  useEffect(() => { void Promise.all([obtenerPerfilPublico(slug), obtenerPrestacionesPublicas(slug)]).then(([p, s]) => { setPerfil(p); setItems(s); setEstado("form"); trackEvent("public_booking_view", { source: "public_booking" }); capturePostHogEvent("public_booking_view", { source: "public_booking" }); }).catch(() => { setMensaje("Este enlace de reservas no está disponible."); setEstado("error"); }); }, [slug]);
  useEffect(() => { if (!sel || !fecha) return; void obtenerDisponibilidadPublica(slug, sel, fecha).then(d => { setHorarios(d.dias[0]?.horarios ?? []); trackEvent("public_booking_availability_view", { source: "public_booking" }); capturePostHogEvent("public_booking_availability_view", { source: "public_booking" }); }).catch(() => setHorarios([])); }, [slug, sel, fecha]);
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!sel || !hora) return; trackEvent("public_booking_attempt", { source: "public_booking" }); capturePostHogEvent("public_booking_attempt", { source: "public_booking" }); try { const r = await crearReservaPublica(slug, { prestacion: sel, fecha_hora: hora, paciente: datos }); setReserva(r); setEstado("confirmado"); trackEvent("public_booking_success", { source: "public_booking" }); capturePostHogEvent("public_booking_success", { source: "public_booking" }); } catch (error) { setMensaje("No pudimos reservar ese horario. Intentá nuevamente."); trackEvent("public_booking_error", { source: "public_booking", error_type: "server_error" }); capturePostHogEvent("public_booking_error", { source: "public_booking", error_type: normalizePostHogError(error) }); } }
  async function submitEspera(e: React.FormEvent) { e.preventDefault(); if (enviandoEspera || !sel || !fecha) return; if (!fechaHastaEspera || fechaHastaEspera < fecha) { setErrorEspera("La fecha hasta debe ser igual o posterior a la fecha desde."); return; } if (waitlistTime.desde && (!waitlistTime.hasta || waitlistTime.hasta <= waitlistTime.desde)) { setErrorEspera("La hora hasta debe ser posterior a la hora desde."); return; } setEnviandoEspera(true); setErrorEspera(""); try { await crearWaitlistPublica(slug, { prestacion: sel, fecha_desde: fecha, fecha_hasta: fechaHastaEspera, ...(waitlistTime.desde ? { hora_desde: waitlistTime.desde, hora_hasta: waitlistTime.hasta } : {}), paciente: datos }); setEsperaEnviada(true); trackEvent("public_waitlist_success", { source: "public_booking" }); } catch { setErrorEspera("No pudimos sumarte a la lista de espera. Revisá los datos e intentá nuevamente."); trackEvent("public_waitlist_error", { source: "public_booking", error_type: "server_error" }); } finally { setEnviandoEspera(false); } }
  function alternarEspera() { setModoEspera((actual) => !actual); setFechaHastaEspera((actual) => actual || fecha); setErrorEspera(""); }
  if (estado === "loading") return <main className="public-booking"><p>Cargando disponibilidad…</p></main>;
  if (estado === "error") return <main className="public-booking"><h1>{mensaje}</h1></main>;
  if (estado === "confirmado" && reserva) return <main className="public-booking"><section className="public-card"><h1>Tu turno fue reservado</h1><p>{reserva.profesional.nombre} {reserva.profesional.apellido} · {reserva.prestacion.nombre}</p><p>{formatoFechaHoraPublica(reserva.fecha_hora)}</p><a href={"/reserva/" + reserva.autogestion_token}>Gestionar mi turno</a><p>Te enviamos un email con los detalles y un enlace para gestionar tu turno.</p></section></main>;
  return <main className="public-booking"><section className="public-card"><p className="public-kicker">Turnelia</p><h1>Reservá tu turno</h1><h2>{perfil?.nombre} {perfil?.apellido}</h2><label>Prestación<select value={sel} onChange={e => { setSel(e.target.value); setHora(""); setEsperaEnviada(false); }}><option value="">Elegí una prestación</option>{items.map(p => <option key={p.identificador_publico} value={p.identificador_publico}>{p.nombre} · {p.duracion_minutos} min · {p.modalidad}</option>)}</select></label>{sel && <label>Fecha<input type="date" value={fecha} onChange={e => { setFecha(e.target.value); setHora(""); setEsperaEnviada(false); }} /></label>}{fecha && <fieldset><legend>Horarios disponibles</legend>{horarios.length ? horarios.map(h => <button type="button" key={h} className={hora === h ? "selected" : ""} onClick={() => setHora(h)}>{formatoHoraPublica(h)}</button>) : <p>No hay horarios disponibles para este día.</p>}</fieldset>}
    {sel && fecha && !esperaEnviada && <div className="public-waitlist-prompt"><strong>¿No encontraste un horario que te sirva?</strong><p>Dejanos tus preferencias y te avisamos por email si se libera un turno compatible.</p><button type="button" className="public-button-secondary" onClick={alternarEspera}>{modoEspera ? "Volver a reservar" : "Sumarme a la lista de espera"}</button></div>}
    {modoEspera && !esperaEnviada ? <form onSubmit={submitEspera}><div className="public-waitlist-range"><label>Desde<input required type="date" value={fecha} onChange={e => setFecha(e.target.value)} /></label><label>Hasta<input required type="date" value={fechaHastaEspera} min={fecha} onChange={e => setFechaHastaEspera(e.target.value)} /></label><label>Hora desde<input type="time" value={waitlistTime.desde} onChange={e => setWaitlistTime({ ...waitlistTime, desde: e.target.value })} /></label><label>Hora hasta<input type="time" value={waitlistTime.hasta} onChange={e => setWaitlistTime({ ...waitlistTime, hasta: e.target.value })} /></label></div>{(["nombre", "apellido", "email", "telefono", "dni"] as const).map(c => <label key={c}>{c[0].toUpperCase() + c.slice(1)}<input required={c === "nombre" || c === "apellido" || c === "email"} type={c === "email" ? "email" : "text"} value={datos[c]} onChange={e => setDatos({ ...datos, [c]: e.target.value })} /></label>)}{errorEspera && <p className="public-feedback public-feedback-error" role="alert">{errorEspera}</p>}<button type="submit" disabled={enviandoEspera}>{enviandoEspera ? "Enviando…" : "Confirmar lista de espera"}</button></form> : <form onSubmit={submit}>{(["nombre", "apellido", "email", "telefono", "dni"] as const).map(c => <label key={c}>{c[0].toUpperCase() + c.slice(1)}<input required={c === "nombre" || c === "apellido" || c === "email"} type={c === "email" ? "email" : "text"} value={datos[c]} onChange={e => setDatos({ ...datos, [c]: e.target.value })} /></label>)}<button type="submit" disabled={!hora}>Reservar turno</button></form>}
    {esperaEnviada && <div className="public-feedback public-feedback-success" role="status"><strong>Quedaste en la lista de espera</strong><span>Te avisaremos por email si aparece un horario compatible.</span></div>}
  </section></main>;
}
