import { useEffect, useState } from "react";
import axios from "axios";
import { confirmarPublicStudyDocumento, crearPublicStudyUploadIntent, finalizarPublicStudy, obtenerStudyRequestPublica, removerPublicStudyDocumento, subirAStorage } from "../services/studyAccessService";
import type { PublicStudyRequest } from "../types/paciente";
import "./StudyUploadAccess.css";

const MAX_SIZE = 10 * 1024 * 1024;
const TYPES = new Set(["application/pdf", "image/jpeg", "image/png", "image/webp"]);
type Uploaded = { id: number; name: string; size: number };
function errorText(error: unknown) { return axios.isAxiosError(error) && typeof error.response?.data?.detail === "string" ? error.response.data.detail : "No se pudo completar la operación."; }
export default function StudyUploadAccess() {
  const token = new URLSearchParams(window.location.search).get("token");
  const [item, setItem] = useState<PublicStudyRequest | null>(null); const [state, setState] = useState(token ? "loading" : "invalid"); const [files, setFiles] = useState<Uploaded[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [submitted, setSubmitted] = useState(false);
  useEffect(() => { if (!token) return; let active = true; obtenerStudyRequestPublica(token).then((value) => { if (active) { setItem(value); setState("ready"); } }).catch((e) => { if (active) setState(axios.isAxiosError(e) && e.response?.status === 404 ? "invalid" : "error"); }); return () => { active = false; }; }, [token]);
  async function upload(file: File) { if (!token || busy) return; if (!TYPES.has(file.type) || file.size <= 0 || file.size > MAX_SIZE) { setError("PDF, JPG, PNG o WebP. Máximo 10 MB por archivo."); return; } if (files.length >= 5) { setError("Podés enviar hasta 5 archivos."); return; } setBusy(true); setError(""); try { const intent = await crearPublicStudyUploadIntent(token, file); await subirAStorage(intent.upload_url, file, intent.required_content_type); await confirmarPublicStudyDocumento(token, intent.document_id); setFiles((current) => [...current, { id: intent.document_id, name: file.name, size: file.size }]); } catch (e) { setError(e instanceof Error && e.message === "upload" ? "No se pudo cargar el archivo." : errorText(e)); } finally { setBusy(false); } }
  async function remove(id: number) { if (!token || busy) return; setBusy(true); setError(""); try { await removerPublicStudyDocumento(token, id); setFiles((current) => current.filter((file) => file.id !== id)); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function submit() { if (!token || !files.length || busy) return; setBusy(true); setError(""); try { await finalizarPublicStudy(token); setSubmitted(true); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  if (state === "loading") return <main className="study-access-page"><section className="study-access-card"><p>Cargando solicitud...</p></section></main>;
  if (state === "invalid") return <main className="study-access-page"><section className="study-access-card"><h1>Enlace no disponible</h1><p>Este enlace no es válido o ya no está disponible.</p></section></main>;
  if (state === "error") return <main className="study-access-page"><section className="study-access-card"><h1>No pudimos cargar la solicitud</h1><p>Intentá nuevamente más tarde.</p></section></main>;
  if (submitted) return <main className="study-access-page"><section className="study-access-card"><h1>Resultados enviados correctamente</h1><p>El profesional ya puede revisar los archivos que enviaste.</p></section></main>;
  return <main className="study-access-page"><section className="study-access-card"><p className="study-access-eyebrow">Turnelia</p><h1>Solicitud de estudio</h1><dl><div><dt>Profesional</dt><dd>{item?.professional_name}</dd></div><div><dt>Estudio solicitado</dt><dd>{item?.title}</dd></div>{item?.instructions && <div><dt>Indicaciones</dt><dd>{item.instructions}</dd></div>}<div><dt>Estado</dt><dd>Pendiente</dd></div></dl><h2>Enviar resultados</h2><p>PDF, JPG, PNG o WebP. Máximo 10 MB por archivo.</p><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" disabled={busy || files.length >= 5} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} />{error && <p role="alert">{error}</p>}<ul>{files.map((file) => <li key={file.id}>{file.name} <button type="button" onClick={() => void remove(file.id)} disabled={busy}>Quitar</button></li>)}</ul><button type="button" disabled={!files.length || busy} onClick={() => void submit()}>{busy ? "Procesando…" : "Finalizar envío"}</button></section></main>;
}
